services:
  db:
    image: postgres:17
    container_name: postgres-db
    networks:
      - custom-network
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    volumes:
      - postgres-volume:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    container_name: adminer-web
    networks:
      - custom-network
    ports:
      - 8000:8080
    environment:
      PGADMIN_DEFAULT_EMAIL: ritam@example.com
      PGADMIN_DEFAULT_PASSWORD: password

networks:
  custom-network:
    driver: bridge

volumes:
  postgres-volume:
    external: true
