services:
  db:
    image: postgres:17
    container_name: postgres-db
    networks:
      - custom-network
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    volumes:
      - postgres-volume:/var/lib/postgresql/data

  cacheDB:
    image: redis:8-alpine
    container_name: redis-cache
    networks:
      - custom-network
    ports:
      - 6379:6379
    volumes:
      - redis-volume:/data

networks:
  custom-network:
    driver: bridge

volumes:
  postgres-volume:
    external: true
  redis-volume:

